/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import static java.lang.Thread.sleep;
import java.util.List;
import javax.swing.JFileChooser;
import logica.Tiempo;
import logica.VentasDB;

/**
 *
 * @author luis_
 */
public class FrameRepVentas extends javax.swing.JInternalFrame implements Runnable {

    Color fondoBg = new Color(43, 43, 43); //Gris Oscuro
    Color fondoPanel = new Color(69, 73, 74); //Gris Medio
    Color Texto = new Color(102, 102, 102); //Gris Claro

    Notificaciones mensajes = new Notificaciones();
    VentasDB ventasBD = new VentasDB();
    Tiempo tiempo = new Tiempo();

    int i = 1;
    private boolean tarea = false;
    private int thilo = 50;

    /**
     * Creates new form FrameRepVendedores
     */
    public FrameRepVentas() {
        initComponents();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jDCFecha3 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jDCFecha4 = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jBLimpiar2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jBExtraer = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setClosable(true);
        setTitle("Modulo Reporte de Ventas por factura");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Reportes de Ventas por Factura");

        jDCFecha3.setForeground(new java.awt.Color(255, 255, 255));
        jDCFecha3.setDateFormatString("yyyy-MM-dd");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Inicio:");

        jDCFecha4.setDateFormatString("yyyy-MM-dd");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Fin:");

        jBLimpiar2.setBackground(fondoPanel);
        jBLimpiar2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBLimpiar2.setForeground(new java.awt.Color(255, 255, 255));
        jBLimpiar2.setText("Limpiar");
        jBLimpiar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBLimpiar2.setFocusPainted(false);
        jBLimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar2ActionPerformed(evt);
            }
        });

        jBExtraer.setBackground(fondoPanel);
        jBExtraer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBExtraer.setForeground(new java.awt.Color(255, 255, 255));
        jBExtraer.setText("Extraer");
        jBExtraer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBExtraer.setFocusPainted(false);
        jBExtraer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExtraerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDCFecha4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDCFecha3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jBExtraer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBLimpiar2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBExtraer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBLimpiar2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDCFecha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(jDCFecha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(jLabel15)))
                        .addGap(45, 45, 45)))
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar2ActionPerformed
        limpiar();
    }//GEN-LAST:event_jBLimpiar2ActionPerformed

    private void jBExtraerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExtraerActionPerformed
        reporte();
    }//GEN-LAST:event_jBExtraerActionPerformed
    private void limpiar() {
        jDCFecha3.setDate(null);
        jDCFecha4.setDate(null);
        jProgressBar1.setValue(0);
    }

    private void reporte() {
        Thread hilo1 = new Thread(this);
        hilo1.start();
    }

    @Override
    public void run() {
        String fecha1 = tiempo.formatoFecha(jDCFecha3.getDate());
        String fecha2 = tiempo.formatoFecha(jDCFecha4.getDate());

        try {
            List<Object[]> reporte = ventasBD.reporteVentas(fecha1, fecha2);

            if (reporte.isEmpty()) {
                mensajes.notificar("Las Fechas Seleccionadas No tiene Ventas");
            } else {
                int ciclo = (int) ((100 * 1) / reporte.size());
                int sumado = ciclo;
                
                String datos = "Detalle;Factura;Nombre Libro;Cantida;Precio Unidad;Nombre Cliete;Nombre Vendedor;Fecha Venta";

                JFileChooser guardarArchivo = new JFileChooser();
                guardarArchivo.setApproveButtonText("Guardar");
                guardarArchivo.showSaveDialog(null);
                
                File archivo = new File(guardarArchivo.getSelectedFile() + ".csv");
         
                if(!archivo.exists()){
                    archivo.createNewFile();
                }

                FileWriter escribir = new FileWriter(archivo);

                for (int i = 0; i < reporte.size(); i++) {
                    Object[] rp = new Object[8];
                    rp = reporte.get(i);
                    datos = datos + "\n";
                    
                    for (int j = 0; j < 8; j++) {
                        datos = datos + rp[j] + ";";
                    }
                    
                    if (!(sumado > 100)) {
                        sumado = sumado + ciclo;
                        jProgressBar1.setValue(sumado);
                        jProgressBar1.repaint();
                        sleep(250);
                    }
                }
                
                for (int j = 0; j < datos.length(); j++) {
                    escribir.write(datos.charAt(j));
                }
                
                escribir.close();
               
                jProgressBar1.setValue(100);
                jProgressBar1.repaint();
                System.out.println(datos);
                mensajes.notificar("Se ha descargado el Archivo");
            }

        } catch (Exception e) {
            mensajes.error("Error al Descargar el Reporte " + e.getMessage());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBExtraer;
    private javax.swing.JButton jBLimpiar2;
    private com.toedter.calendar.JDateChooser jDCFecha3;
    private com.toedter.calendar.JDateChooser jDCFecha4;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

}
