/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import logica.ClienteBD;
import logica.Cliente;
import logica.DetalleVentas;
import logica.LibroBD;
import logica.Libro;
import logica.Tiempo;
import logica.Vendedor;
import logica.Ventas;
import logica.VentasDB;

/**
 *
 * @author luis_
 */
public class FrameVentas extends javax.swing.JInternalFrame {

    Personalizar personalizar = new Personalizar();
    ClienteBD clienteDB = new ClienteBD();
    Cliente cliente = new Cliente();
    LibroBD libroDB = new LibroBD();
    Vendedor vendedor = new Vendedor();
    Notificaciones mensaje = new Notificaciones();
    Tiempo tiempo = new Tiempo();
    Libro libro = new Libro();
    DefaultTableModel modelo = new DefaultTableModel();
    Ventas v = new Ventas();
    VentasDB ventasDB = new VentasDB();
    DetalleVentas Dv = new DetalleVentas();

    double precioLibro;
    int cantidad;
    double subtotalPagar;
    double impPagar;
    double total;
    final double impuesto = 0.13;

    public FrameVentas(Vendedor vendedor) {

        initComponents();
        this.vendedor = vendedor;
        jTVendedor.setText(vendedor.getNombreVendedor() + " " + vendedor.getApellidoVendedor());
        generaSerieFactura();

    }

    public void generaSerieFactura() {
        String serie = ventasDB.idVentas();
        System.out.println(serie);
        if (serie == null || serie.equalsIgnoreCase("")) {
            jTFactura.setText("0000001");
        } else {
            int incremento = Integer.parseInt(serie);
            incremento = incremento + 1;
            jTFactura.setText("000000" + incremento);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFactura = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTVendedor = new javax.swing.JTextField();
        jBCancelar = new javax.swing.JButton();
        jTSubTotal = new javax.swing.JTextField();
        jLSubTotal = new javax.swing.JLabel();
        jBVender = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLSubTotal1 = new javax.swing.JLabel();
        jTTotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTPrecio = new javax.swing.JTextField();
        jBAgregar = new javax.swing.JButton();
        jTCodCliente = new javax.swing.JTextField();
        jBBuscarClie = new javax.swing.JButton();
        jBBuscarProd = new javax.swing.JButton();
        jTCodProducto = new javax.swing.JTextField();
        jSCantidad = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jTProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTStock = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTVentas = new javax.swing.JTable();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setClosable(true);
        setTitle("Ventas");
        setAutoscrolls(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo pequeño.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de Punto de Venta FideLibro ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero de Factura :");

        jTFactura.setBackground(personalizar.Texto);
        jTFactura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTFactura.setForeground(new java.awt.Color(255, 255, 255));
        jTFactura.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Vendedor:");

        jTVendedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTVendedor.setForeground(new java.awt.Color(255, 255, 255));
        jTVendedor.setEnabled(false);
        jTVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTVendedorActionPerformed(evt);
            }
        });

        jBCancelar.setBackground(personalizar.fondoPanel);
        jBCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBCancelar.setText("Cancelar");
        jBCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBCancelar.setDefaultCapable(false);
        jBCancelar.setFocusPainted(false);
        jBCancelar.setFocusable(false);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jTSubTotal.setEditable(false);
        jTSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        jTSubTotal.setEnabled(false);
        jTSubTotal.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jTSubTotal.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLSubTotal.setText("SubTotal:");

        jBVender.setBackground(personalizar.fondoPanel);
        jBVender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBVender.setForeground(new java.awt.Color(255, 255, 255));
        jBVender.setText("Vender");
        jBVender.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBVender.setDefaultCapable(false);
        jBVender.setFocusPainted(false);
        jBVender.setFocusable(false);
        jBVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVenderActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Fecha: " + tiempo.fechaHoy());

        jLSubTotal1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLSubTotal1.setForeground(new java.awt.Color(255, 255, 255));
        jLSubTotal1.setText("Total:");

        jTTotal.setEditable(false);
        jTTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTTotal.setForeground(new java.awt.Color(255, 255, 255));
        jTTotal.setEnabled(false);
        jTTotal.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jTTotal.setSelectionColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBVender, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jLSubTotal1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLSubTotal))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLSubTotal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVender, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSubTotal1)
                    .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cod. Cliente:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cod. Producto:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad:");

        jTPrecio.setEditable(false);
        jTPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTPrecio.setForeground(new java.awt.Color(255, 255, 255));

        jBAgregar.setBackground(personalizar.fondoPanel);
        jBAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jBAgregar.setText("Agregar");
        jBAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBAgregar.setFocusPainted(false);
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jTCodCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTCodCliente.setForeground(new java.awt.Color(255, 255, 255));

        jBBuscarClie.setBackground(personalizar.fondoPanel);
        jBBuscarClie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBBuscarClie.setForeground(new java.awt.Color(255, 255, 255));
        jBBuscarClie.setText("Buscar");
        jBBuscarClie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBBuscarClie.setFocusPainted(false);
        jBBuscarClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarClieActionPerformed(evt);
            }
        });

        jBBuscarProd.setBackground(personalizar.fondoPanel);
        jBBuscarProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBBuscarProd.setForeground(new java.awt.Color(255, 255, 255));
        jBBuscarProd.setText("Buscar");
        jBBuscarProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBBuscarProd.setFocusPainted(false);
        jBBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarProdActionPerformed(evt);
            }
        });

        jTCodProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTCodProducto.setForeground(new java.awt.Color(255, 255, 255));

        jSCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jSCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cliente:");

        jTProducto.setEditable(false);
        jTProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTProducto.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Producto:");

        jTCliente.setEditable(false);
        jTCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTCliente.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Stock:");

        jTStock.setEditable(false);
        jTStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTStock.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTCodCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jTPrecio)
                    .addComponent(jTCodProducto))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jBBuscarProd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                        .addComponent(jBAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                    .addComponent(jBBuscarClie, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jTStock)))))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBBuscarClie)
                            .addComponent(jTCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBAgregar)
                                    .addComponent(jTPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jSCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBBuscarProd)
                                    .addComponent(jTCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTVentas.setBackground(personalizar.Texto);
        jTVentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTVentas.setForeground(new java.awt.Color(255, 255, 255));
        jTVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orden", "Cod", "Productos", "Cantidad", "Precio", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTVentas.setFillsViewportHeight(true);
        jTVentas.setGridColor(new java.awt.Color(204, 204, 204));
        jTVentas.setInheritsPopupMenu(true);
        jTVentas.setMaximumSize(new java.awt.Dimension(0, 0));
        jTVentas.setMinimumSize(new java.awt.Dimension(0, 0));
        jTVentas.setRowHeight(35);
        jTVentas.setShowGrid(true);
        jTVentas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTVentas);
        if (jTVentas.getColumnModel().getColumnCount() > 0) {
            jTVentas.getColumnModel().getColumn(0).setResizable(false);
            jTVentas.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTVentas.getColumnModel().getColumn(1).setResizable(false);
            jTVentas.getColumnModel().getColumn(1).setPreferredWidth(5);
            jTVentas.getColumnModel().getColumn(2).setResizable(false);
            jTVentas.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTVentas.getColumnModel().getColumn(3).setResizable(false);
            jTVentas.getColumnModel().getColumn(3).setPreferredWidth(5);
            jTVentas.getColumnModel().getColumn(4).setResizable(false);
            jTVentas.getColumnModel().getColumn(4).setPreferredWidth(10);
            jTVentas.getColumnModel().getColumn(5).setResizable(false);
            jTVentas.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        agregar();
        limpiarAgregar();
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        limpiartabla(); 
        limpiarCampos();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTVendedorActionPerformed

    private void jBVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVenderActionPerformed

        if (jTTotal.getText().equals("")) {
            mensaje.error("Debe de Ingresar Productos para Vender");
        } else {
            guardarVentas();
            guardarDetalle();
            actualizaStock();
            mensaje.notificar("Se ha Generado la Venta");
            limpiarCampos();
        }

    }//GEN-LAST:event_jBVenderActionPerformed

    private void jBBuscarClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarClieActionPerformed
        buscarCliente();
    }//GEN-LAST:event_jBBuscarClieActionPerformed

    private void jBBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarProdActionPerformed
        buscarProducto();
    }//GEN-LAST:event_jBBuscarProdActionPerformed
    public void actualizaStock() {
        for (int i = 0; i < jTVentas.getRowCount(); i++) {
            Libro libro = new Libro();
            int IdProducto = Integer.parseInt(jTVentas.getValueAt(i, 1).toString());
            int cantidad = Integer.parseInt(jTVentas.getValueAt(i, 3).toString());
            libro = libroDB.listarID(IdProducto);
            int StockAcutal = (libro.getStock()) - cantidad;

            libroDB.ActualizarStockLibro(StockAcutal, IdProducto);
        }

    }

    public void guardarVentas() {
        int idvendedor = vendedor.getIdVendedor();
        int idCliente = cliente.getId();
        double monto = subtotalPagar;

        v.setIdVendedor(idvendedor);
        v.setIdCliente(idCliente);
        v.setTotalVenta(monto);
        ventasDB.GuardarVentas(v);
    }

    public void guardarDetalle() {
        int IdVenta;

        if (ventasDB.idVentas() == null || (ventasDB.idVentas()).equalsIgnoreCase("")) {
            IdVenta = 1;
        } else {
            IdVenta = Integer.parseInt(ventasDB.idVentas());
        }
        System.out.println("Detalle idVenta" + IdVenta);

        for (int i = 0; i < jTVentas.getRowCount(); i++) {
            int idProducto = Integer.parseInt(jTVentas.getValueAt(i, 1).toString());
            int cantidad = Integer.parseInt(jTVentas.getValueAt(i, 3).toString());
            double precioVentas = Double.parseDouble(jTVentas.getValueAt(i, 4).toString());

            Dv.setVentaId(IdVenta);
            Dv.setLibroProducto(idProducto);
            Dv.setCantidad(cantidad);
            Dv.setPrecioVenta(precioVentas);

            ventasDB.GuardarDetalleVentas(Dv);
        }

    }

    public void agregar() {
        int item = 0;
        double total;

        modelo = (DefaultTableModel) jTVentas.getModel();
        item = item + 1;
        int idp = libro.getIdLibro();
        String nombLibro = jTProducto.getText();
        precioLibro = Double.parseDouble(jTPrecio.getText());
        cantidad = (Integer) jSCantidad.getValue();
        int stock = Integer.parseInt(jTStock.getText());
        total = cantidad * precioLibro;

        ArrayList lista = new ArrayList();
        if (stock > 0 && (stock - cantidad) > 0) {
            lista.add(item);
            lista.add(idp);
            lista.add(nombLibro);
            lista.add(cantidad);
            lista.add(precioLibro);
            lista.add(total);
            Object[] ob = new Object[6];
            ob[0] = lista.get(0);
            ob[1] = lista.get(1);
            ob[2] = lista.get(2);
            ob[3] = lista.get(3);
            ob[4] = lista.get(4);
            ob[5] = lista.get(5);
            modelo.addRow(ob);
            jTVentas.setModel(modelo);

            calcularTotales();

        } else if (stock < 0) {
            mensaje.error("El Stock del Libro " + nombLibro + " No esta disponible");
        } else if ((stock - cantidad) < 0) {
            mensaje.error("El Stock del Libro " + nombLibro + " No dispone la Cantidad Solicitada");
        }
    }

    public void calcularTotales() {
        subtotalPagar = 0;
        for (int i = 0; i < modelo.getRowCount(); i++) {
            cantidad = Integer.parseInt(modelo.getValueAt(i, 3).toString());
            precioLibro = Double.parseDouble(modelo.getValueAt(i, 4).toString());
            subtotalPagar = subtotalPagar + cantidad * precioLibro;
        }
        impPagar = subtotalPagar * impuesto;
        total = subtotalPagar + impPagar;
        jTSubTotal.setText("₡" + subtotalPagar);
        jTTotal.setText("₡" + total);
    }

    public void buscarCliente() {
        boolean respuesta;
        String idCliente = jTCodCliente.getText();
        if (jTCodCliente.getText().length() == 0) {
            mensaje.error("Debe de indicar la Ced del Cliente");
        } else if (Integer.parseInt(jTCodCliente.getText()) == 0) {
            mensaje.error("Error con el Codigo Producto 0");
        } else {
            cliente = clienteDB.ListarId(idCliente);

            if (String.valueOf(cliente.getCedCliente()).equalsIgnoreCase(idCliente)) {

                jTCliente.setText(cliente.getNombreCliente() + " " + cliente.getApellidoCliente());
                jTCodProducto.requestFocus();
            } else {
                respuesta = mensaje.confirmar("Cliente no Registrado, Desea Registrarlo?", "Error no se encuentra Cliente");
                if (respuesta) {
                    FrameClientes cf = new FrameClientes();
                    Principal.VentanaPrincipal.add(cf);
                    cf.setVisible(true);
                }
            }

        }

    }

    public void buscarProducto() {
        boolean respuesta;
        String idProducto = jTCodProducto.getText();
        if (jTCodProducto.getText().length() == 0) {
            mensaje.error("Debe de indicar el Codigo del Libro");
        } else if (Integer.parseInt(jTCodProducto.getText()) == 0) {
            mensaje.error("Error con el Codigo Producto 0");
        } else {
            libro = libroDB.listarID(Integer.parseInt(idProducto));

            if (String.valueOf(libro.getIdLibro()).equalsIgnoreCase(idProducto)) {//incluir validacion de buscar el codigo o nombre del libro 
                jTCodProducto.setText(String.valueOf(libro.getIdLibro()));
                jTProducto.setText(libro.getNombreLibro());
                jTPrecio.setText(String.valueOf(libro.getPrecio()));
                jTStock.setText(String.valueOf(libro.getStock()));
            } else {
                respuesta = mensaje.confirmar("Codigo de Producto incorrecto, Desea Buscarlo?", "Error con el Codigo");
                if (respuesta) {
                    FrameLibros lb = new FrameLibros();
                    Principal.VentanaPrincipal.add(lb);
                    lb.setVisible(true);
                }
            }

        }
    }

    public void limpiarCampos() {
        jTSubTotal.setText("");
        jTTotal.setText("");
        jTCodCliente.setText("");
        jTCliente.setText("");
        jTCodProducto.setText("");
        jTProducto.setText("");
        jTPrecio.setText("");
        jTStock.setText("");
        jSCantidad.setValue(1);

        jTCodCliente.requestFocus();
        jTVendedor.setText(vendedor.getNombreVendedor() + " " + vendedor.getApellidoVendedor());
        generaSerieFactura();
        limpiartabla();
    }

    public void limpiarAgregar() {
        jTCodProducto.setText("");
        jTProducto.setText("");
        jTPrecio.setText("");
        jTStock.setText("");
        jSCantidad.setValue(1);

        jTCodProducto.requestFocus();
    }

    public void limpiartabla() {

        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBuscarClie;
    private javax.swing.JButton jBBuscarProd;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBVender;
    private javax.swing.JLabel jLSubTotal;
    private javax.swing.JLabel jLSubTotal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSCantidad;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTCliente;
    private javax.swing.JTextField jTCodCliente;
    private javax.swing.JTextField jTCodProducto;
    private javax.swing.JTextField jTFactura;
    private javax.swing.JTextField jTPrecio;
    private javax.swing.JTextField jTProducto;
    private javax.swing.JTextField jTStock;
    private javax.swing.JTextField jTSubTotal;
    private javax.swing.JTextField jTTotal;
    private javax.swing.JTextField jTVendedor;
    private javax.swing.JTable jTVentas;
    // End of variables declaration//GEN-END:variables
}
